<script lang="ts">
  import type { LoadingController } from './loading'

  export let controller: LoadingController
  export let color = '#eaeaea'
</script>

{#if $controller}
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    style="margin: auto; display: block; shape-rendering: auto; animation-play-state: running; animation-delay: 0s;"
    width="200px"
    viewBox="0 0 100 100"
    preserveAspectRatio="xMidYMid"
  >
    <circle
      cx="50"
      cy="50"
      fill="none"
      stroke={color}
      stroke-width="15"
      r="35"
      stroke-dasharray="164.93361431346415 56.97787143782138"
      style="animation-play-state: running; animation-delay: 0s;"
    >
      <animateTransform
        attributeName="transform"
        type="rotate"
        repeatCount="indefinite"
        dur="1s"
        values="0 50 50;360 50 50"
        keyTimes="0;1"
        style="animation-play-state: running; animation-delay: 0s;"
      />
    </circle>
    <!-- [ldio] generated by https://loading.io/ -->
  </svg>
{/if}

<style>
  svg {
    max-width: 100%;
    max-height: 100%;
  }
</style>
